### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by contrapunctus-1** [physphil/UnitConverterUltimate#235]
Running v5.7.2, installed from F-Droid, on a Nokia 6.1.

logcat output -
```
01-14 11:45:12.542 I/ActivityManager(1624): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.physphil.android.unitconverterultimate/.MainActivity bnds=[392,1053][594,1253] (has extras)} from uid 10098
01-14 11:45:12.544 I/ActivityManager(1624): Message Object: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.physphil.android.unitconverterultimate/.MainActivity bnds=[392,1053][594,1253] (has extras) }
01-14 11:45:12.626 D/ActivityTrigger(1624): activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{76e7626 com.physphil.android.unitconverterultimate}
01-14 11:45:12.626 E/ActivityTrigger(1624): activityStartTrigger: not whiteListedcom.physphil.android.unitconverterultimate/com.physphil.android.unitconverterultimate.MainActivity/50702
01-14 11:45:12.627 D/ActivityTrigger(1624): activityResumeTrigger: The activity in ApplicationInfo{76e7626 com.physphil.android.unitconverterultimate} is now in focus and seems to be in full-screen mode
01-14 11:45:12.627 E/ActivityTrigger(1624): activityResumeTrigger: not whiteListedcom.physphil.android.unitconverterultimate/com.physphil.android.unitconverterultimate.MainActivity/50702
01-14 11:45:12.640 D/ActivityTrigger(1624): activityResumeTrigger: The activity in ApplicationInfo{76e7626 com.physphil.android.unitconverterultimate} is now in focus and seems to be in full-screen mode
01-14 11:45:12.640 E/ActivityTrigger(1624): activityResumeTrigger: not whiteListedcom.physphil.android.unitconverterultimate/com.physphil.android.unitconverterultimate.MainActivity/50702
01-14 11:45:12.644 D/ActivityManager(1624): Package [com.physphil.android.unitconverterultimate] have process
01-14 11:45:12.648 I/PhoneWindow(1624): isAPPNeedChange pkgName: com.physphil.android.unitconverterultimate needKeep: false
01-14 11:45:12.664 I/ActivityManager(1624): Start proc 11453:com.physphil.android.unitconverterultimate/u0a64 for activity com.physphil.android.unitconverterultimate/.MainActivity
01-14 11:45:12.665 D/ActivityManager(1624): handleProcessStartedLocked mDoneFinishBooting && app.pid != 0 ---> notifyProcessStart, app.processName = com.physphil.android.unitconverterultimate, app.info = ApplicationInfo{76e7626 com.physphil.android.unitconverterultimate}, app.hostingType = activity, getHostingName() = ComponentInfo{com.physphil.android.unitconverterultimate/com.physphil.android.unitconverterultimate.MainActivity}, getIntentFlag() = 0, getIsPackageRunning() = true, app = ProcessRecord{3f4ab47 11453:com.physphil.android.unitconverterultimate/u0a64}, getExtraData() = Bundle[{ACTIVITY_TASK_AFFINITY=com.physphil.android.unitconverterultimate, ACTIVITY_INTENT=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.physphil.android.unitconverterultimate/.MainActivity bnds=[392,1053][594,1253] (has extras) }, CALLER_PACKAGE=com.android.launcher3, ACTIVITY_INFO=ActivityInfo{15ef180 com.physphil.android.unitconverterultimate.MainActivity}}]
01-14 11:45:12.721 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.722 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.725 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.725 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.733 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.733 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.735 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.735 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.744 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.744 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.757 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.757 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.879 E/AndroidRuntime(11453): Process: com.physphil.android.unitconverterultimate, PID: 11453
01-14 11:45:12.879 E/AndroidRuntime(11453): java.lang.RuntimeException: Unable to create application com.physphil.android.unitconverterultimate.UnitConverterApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
01-14 11:45:12.879 E/AndroidRuntime(11453): 	at com.physphil.android.unitconverterultimate.util.Conversions.updateCurrencyConversions(Conversions.java:145)
01-14 11:45:12.879 E/AndroidRuntime(11453): 	at com.physphil.android.unitconverterultimate.UnitConverterApplication.onCreate(UnitConverterApplication.java:36)
01-14 11:45:12.883 W/ActivityManager(1624):   Force finishing activity com.physphil.android.unitconverterultimate/.MainActivity
01-14 11:45:12.889 D/StatusBarManagerService(1624): manageDisableList userId=0 what=0x0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.889 D/StatusBarManagerService(1624): disableLocked net1 = 0; net2 = 0 pkg=Window{227436b u0 Splash Screen com.physphil.android.unitconverterultimate}
01-14 11:45:12.912 I/ActivityManager(1624): Process com.physphil.android.unitconverterultimate (pid 11453) has died: fore TOP 
01-14 11:45:12.917 W/SurfaceFlinger(763): Attempting to set client state on removed layer: Splash Screen com.physphil.android.unitconverterultimate#0
01-14 11:45:12.917 W/SurfaceFlinger(763): Attempting to destroy on removed layer: Splash Screen com.physphil.android.unitconverterultimate#0
01-14 11:45:12.924 W/SurfaceFlinger(763): Attempting to destroy on removed layer: AppWindowToken{fe77d44 token=Token{ed7e57 ActivityRecord{c035bd6 u0 com.physphil.android.unitconverterultimate/.MainActivity t43128}}}#0
01-14 11:45:13.519 I/StabilityMonitor(11495): [ParserUtility] key word : com.physphil.android.unitconverterultimate
01-14 11:45:13.520 I/StabilityMonitor(11495): [APRReport] exceptionItem  tag:data_app_crash packageName:com.physphil.android.unitconverterultimate versionCode:50702 versionName:5.7.2
01-14 11:45:13.628 E/STBIntentService(11495): send error message:data_app_crash;1673676912902(pkgName:com.physphil.android.unitconverterultimate;version:5.7.2;versionCode:50702) to BBS for ANR/FC/TOMB_STONE...
01-14 11:45:13.715 E/STBMonitorQueue(11495): restore data:/data/system/dropbox/data_app_crash@1672972296338.txt;50702;5.7.2;com.physphil.android.unitconverterultimate into regularQue queue...
01-14 11:45:13.716 E/STBMonitorQueue(11495): restore data:/data/system/dropbox/data_app_crash@1672972297929.txt;50702;5.7.2;com.physphil.android.unitconverterultimate into regularQue queue...
01-14 11:45:13.716 E/STBMonitorQueue(11495): restore data:/data/system/dropbox/data_app_crash@1672972299308.txt;50702;5.7.2;com.physphil.android.unitconverterultimate into regularQue queue...
01-14 11:45:13.716 E/STBMonitorQueue(11495): restore data:/data/system/dropbox/data_app_crash@1673520684026.txt;50702;5.7.2;com.physphil.android.unitconverterultimate into regularQue queue...
01-14 11:45:13.718 E/STBMonitorQueue(11495): restore data:/data/system/dropbox/data_app_crash@1673617376564.txt;50702;5.7.2;com.physphil.android.unitconverterultimate into regularQue queue...
01-14 11:45:18.056 D/PowerCalculator(3308): topApCounter com.physphil.android.unitconverterultimate
```

**Comment by tacsipacsi** [comment]
This has already been fixed in #234 and released on Google Play, so all to be done is releasing it on F-Droid as well. @physphil, if you do a GitHub release, F-Droid should pick that up. @contrapunctus-1, in the meantime, you can delete the F-Droid version and download the app from Google Play, if you’re okay with using Google Play.

**Comment by physphil** [comment]
Ah yes, thanks for that. It slipped my mind to create a new release once the issue was fixed, it should be done now.

**Comment by tacsipacsi** [comment]
Maybe you could create a guide for releasing new versions, e.g. in a CONTRIBUTING file, so that you don’t forget it next time?
